<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toxiang</name>
   <tag></tag>
   <elementGuidId>1f70a822-23ab-4bcc-b53c-31cc718f080c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;app&quot;)/div[@class=&quot;honray-scroll-style&quot;]/div[@class=&quot;panel m-w-1280 el-row&quot;]/div[@class=&quot;panel-top m-w-980 common-header&quot;]/div[@class=&quot;p-l-10 p-r-30 m-w-1280 el-row is-justify-space-between el-row--flex&quot;]/div[@class=&quot;el-row is-align-middle el-row--flex&quot;]/div[1]/div[1]/div[@class=&quot;el-dropdown&quot;]/span[@class=&quot;top-icon m-r-16 el-dropdown-selfdefine&quot;]/i[@class=&quot;.m-t-8 fal fa-user-circle&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div/div/div[1]/div[1]/div[3]/div[1]/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>.m-t-8 fal fa-user-circle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;honray-scroll-style&quot;]/div[@class=&quot;panel m-w-1280 el-row&quot;]/div[@class=&quot;panel-top m-w-980 common-header&quot;]/div[@class=&quot;p-l-10 p-r-30 m-w-1280 el-row is-justify-space-between el-row--flex&quot;]/div[@class=&quot;el-row is-align-middle el-row--flex&quot;]/div[1]/div[1]/div[@class=&quot;el-dropdown&quot;]/span[@class=&quot;top-icon m-r-16 el-dropdown-selfdefine&quot;]/i[@class=&quot;.m-t-8 fal fa-user-circle&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div[3]/div/div/div/span/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/i</value>
   </webElementXpaths>
</WebElementEntity>
