<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>sunny</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>843cf1ec-d33c-47cc-8ebe-00cf1ba2ee67</testSuiteGuid>
   <testCaseLink>
      <guid>4d67b78f-b89a-49da-931e-fff00ebabf6e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/sunny/xinli-tianjiabaobei-linshi</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>72143ee5-deb1-4af0-aadd-463c1088ac5c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/sunny</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>72143ee5-deb1-4af0-aadd-463c1088ac5c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>0894c913-f649-4e33-9847-dec19e62c182</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>72143ee5-deb1-4af0-aadd-463c1088ac5c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>7895db34-2e2b-49f5-946c-d317adb36a27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>72143ee5-deb1-4af0-aadd-463c1088ac5c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>gosimingcheng</value>
         <variableId>8e3a320c-1690-4af6-8c75-ce367e7f2514</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>72143ee5-deb1-4af0-aadd-463c1088ac5c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>zhucedizhi</value>
         <variableId>1c313210-a927-41c5-977c-87d0e23be173</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f825027-40ca-4fba-b731-6009ef897815</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f47685cf-9047-4c64-8eb4-350aaab573f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad260fd8-f574-4a40-89ee-a4fc765c2f50</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
