<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fengmian</name>
   <tag></tag>
   <elementGuidId>8f447ac6-349f-4310-9331-198c5b3e1e2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>body.el-popup-parent--hidden:nth-child(2) div.el-dialog__wrapper:nth-child(8) div.el-dialog.key_1598002381_366420 div.key_1598002381_366420Body div.h-100p div.h-100p form.el-form.el-form__self.el-form--label-top div.bg-wh.bor-gray div.el-row:nth-child(3) div.p-l-20.p-r-20 div.el-col.el-col-8 div.form-all-content div.el-form-item.el-form-item--mini.mw-340 div.el-form-item__content div:nth-child(1) div.image-upload-wrap:nth-child(1) div.image-add-wrap div.image-lists > div.image-list</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div[2]/div/div/div/div[2]/form/div[1]/div[2]/div[3]/div/div/div/div/div/div/div/div[1]/div/div/div[1]/label/input</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>key_1597994086_682224</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;key_1597994086_682224&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>file</value>
   </webElementProperties>
</WebElementEntity>
