<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gongzuotai</name>
   <tag></tag>
   <elementGuidId>a14e597a-8659-45be-a7be-32e68bbf8f09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html[1]/body[1]/div[1]/div[1]/div[1]/div[2]/aside[1]/div[1]/div[2]/div[1]/div[1]/span[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
