<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gongsimingcheng</name>
   <tag></tag>
   <elementGuidId>c32f60dc-ceac-4714-ad1c-e82fce35816c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;panelContent&quot;)/div[@class=&quot;grid-content bg-purple-light h-100p&quot;]/div[@class=&quot;h-100p el-col el-col-24&quot;]/div[1]/div[1]/div[@class=&quot;h-100p&quot;]/div[1]/div[1]/div[@class=&quot;bg-wh&quot;]/div[@class=&quot;ovf-y-auto&quot;]/div[1]/div[1]/form[@class=&quot;el-form addReportFrom el-form--label-top&quot;]/div[@class=&quot;p-20 el-row el-row--flex&quot;]/div[@class=&quot;el-col el-col-8&quot;]/div[@class=&quot;w-100p el-row is-align-middle el-row--flex&quot;]/div[@class=&quot;el-form-item is-required mw-340&quot;]/div[@class=&quot;el-form-item__content&quot;]/div[@class=&quot;el-input el-input--samll&quot;]/input[@class=&quot;el-input__inner&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panelContent&quot;)/div[@class=&quot;grid-content bg-purple-light h-100p&quot;]/div[@class=&quot;h-100p el-col el-col-24&quot;]/div[1]/div[1]/div[@class=&quot;h-100p&quot;]/div[1]/div[1]/div[@class=&quot;bg-wh&quot;]/div[@class=&quot;ovf-y-auto&quot;]/div[1]/div[1]/form[@class=&quot;el-form addReportFrom el-form--label-top&quot;]/div[@class=&quot;p-20 el-row el-row--flex&quot;]/div[@class=&quot;el-col el-col-8&quot;]/div[@class=&quot;w-100p el-row is-align-middle el-row--flex&quot;]/div[@class=&quot;el-form-item is-required mw-340&quot;]/div[@class=&quot;el-form-item__content&quot;]/div[@class=&quot;el-input el-input--samll&quot;]/input[@class=&quot;el-input__inner&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='panelContent']/div/div/div/div/div/div/div/div/div[2]/div/div/form/div/div[2]/div/div/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
