<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>zhucedizhishengshiqu</name>
   <tag></tag>
   <elementGuidId>592651a0-7f54-4fe3-b68d-69db1d84330e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='panelContent']/div/div/div/div/div/div/div/div/div[2]/div/div/form/div/div[6]/div/div/div/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-cascader__label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panelContent&quot;)/div[@class=&quot;grid-content bg-purple-light h-100p&quot;]/div[@class=&quot;h-100p el-col el-col-24&quot;]/div[1]/div[1]/div[@class=&quot;h-100p&quot;]/div[1]/div[1]/div[@class=&quot;bg-wh&quot;]/div[@class=&quot;ovf-y-auto&quot;]/div[1]/div[1]/form[@class=&quot;el-form addReportFrom el-form--label-top&quot;]/div[@class=&quot;p-20 el-row el-row--flex&quot;]/div[@class=&quot;el-col el-col-8&quot;]/div[@class=&quot;w-100p el-row is-align-middle el-row--flex&quot;]/div[@class=&quot;el-form-item is-required mw-170&quot;]/div[@class=&quot;el-form-item__content&quot;]/span[@class=&quot;el-cascader&quot;]/span[@class=&quot;el-cascader__label&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='panelContent']/div/div/div/div/div/div/div/div/div[2]/div/div/form/div/div[6]/div/div/div/span/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
   </webElementXpaths>
</WebElementEntity>
