<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>zojingli</name>
   <tag></tag>
   <elementGuidId>460c573d-e96c-4d3c-8d77-951d66051f0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[4]/div/div[2]/div/div/div/div[2]/div[1]/form/div[4]/div/div[1]/div/div/div/div[2]/label[1]/span[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-radio__inner</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[@class=&quot;el-popup-parent--hidden&quot;]/div[@class=&quot;el-dialog__wrapper&quot;]/div[@class=&quot;el-dialog key_1583305428_57426&quot;]/div[@class=&quot;key_1583305428_57426Body&quot;]/div[@class=&quot;h-100p&quot;]/div[@class=&quot;h-100p&quot;]/div[@class=&quot;h-100p&quot;]/div[@class=&quot;rightDiv&quot;]/div[1]/form[@class=&quot;el-form el-form__self el-form--label-top&quot;]/div[@class=&quot;m-t-10&quot;]/div[1]/div[@class=&quot;bg-wh p-10&quot;]/div[@class=&quot;m-b-10&quot;]/div[1]/div[@class=&quot;el-radio-group&quot;]/div[@class=&quot;m-l-20&quot;]/label[@class=&quot;el-radio m-l-20&quot;]/span[@class=&quot;el-radio__input&quot;]/span[@class=&quot;el-radio__inner&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span/span</value>
   </webElementXpaths>
</WebElementEntity>
