<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fanghao</name>
   <tag></tag>
   <elementGuidId>0f9b7c51-e527-4c36-8d17-ff2cc2d54c8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div/div[2]/div/div/div/div[2]/div[1]/form/div[12]/div/div[1]/div/div/div/div/div/div/div/div[2]/div[3]/table/tbody/tr/td[4]/div/div/div/div/div/div/div/div[1]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
