<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>jianzhu</name>
   <tag></tag>
   <elementGuidId>e538c6e7-97c1-4fc7-8bd5-708dc93cb608</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div/div[2]/div/div/div/div[2]/div[1]/form/div[12]/div/div[1]/div/div/div/div/div/div/div/div[2]/div[3]/table/tbody/tr/td[2]/div/div/div/div/div/div/div/div[1]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
