<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>meiyuezujin</name>
   <tag></tag>
   <elementGuidId>ff826330-73ee-4aba-9a54-9b76701c0371</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div/div[2]/div/div/div/div[2]/div[1]/form/div[8]/div/div[2]/div[2]/div/div/div/div/div/div/div/span/div[2]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
