<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>meiyuezohefuwufei</name>
   <tag></tag>
   <elementGuidId>55f74a8c-7321-44a2-addc-f37a9e3f3c66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div/div[2]/div/div/div/div[2]/div[1]/form/div[9]/div/div/div[1]/div/div/div/div/div/div/div/span/div[2]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
