<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>renwudaiban_qiyeruzhu</name>
   <tag></tag>
   <elementGuidId>5143da53-6994-4af5-ab74-eab105c034f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;panelContent&quot;]/div/div/div/div[1]/div[2]/div[2]/div/div/div/div[11]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
