<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wanchengqianding</name>
   <tag></tag>
   <elementGuidId>3e2d8d39-a767-471b-95b7-2197312e8221</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div/div[2]/div/div/div/div[2]/div[1]/form/div[14]/div/div[1]/div/div/div/div[2]/label[1]/span[1]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
