<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gongdanguanli</name>
   <tag></tag>
   <elementGuidId>4514d883-ff38-46bf-97d9-8d2ad6a277e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body//aside[@id='leftMenu']//div//div//div[2]//div[4]//div[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
