<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>daanxuanxiang</name>
   <tag></tag>
   <elementGuidId>3497f559-a7c9-43ae-990c-159b8c7c6bb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body//div[@id='app']//div//div//div//div//div//div//div//div//div//div//div//div//div//div//div//div//div[8]//div[1]//div[1]//div[1]//input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
